### ISSUE TITLE
Data from HN not populating app

### ISSUE THREAD

**Issue by tylerzika** [amitburst/HackerNews#19]
I followed the instructions from Getting Started. The app runs, but no data is being displayed on the app besides an advertisement. 

I'm new to iOS development, so I could be missing something in my Xcode setup.

![screen shot 2015-02-18 at 12 49 44 pm](https://cloud.githubusercontent.com/assets/1011888/6256408/ab36898a-b76c-11e4-82b3-f0a8d49fc9ad.png)
***
![screen shot 2015-02-18 at 12 53 19 pm](https://cloud.githubusercontent.com/assets/1011888/6256457/372a4b48-b76d-11e4-897f-1485680c7298.png)

**Comment by amitburst** [comment]
Ah yeah, I've noticed that posts have been broken for a few days now; sorry about that! This app uses the libHN library which is currently (as of a few hours ago) undergoing some changes that are trying to fix some stuff but haven't quite yet. You can track their progress here: https://github.com/bennyguitar/libHN/commit/87d2a869751d7ccf2c881c4750dcff78316cfe39

I will be sure to update this repo once everything is sorted on their end!

**Comment by tylerzika** [comment]
No worries @amitburst! I'm happy to know that it isn't a problem only I'm having. Thanks for starting this project. I can't wait for for the update!

**Comment by amitburst** [comment]
Phew, that took me far too long; I apologize! Posts should be loading as normally now, @tylerzika!
