### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by dsxNiubility** [amitburst/HackerNews#27]
Do you know how to solve this error
Installing Firebase (2.4.3)

[!] Error installing Firebase
[!] /usr/bin/curl -f -L -o /var/folders/4n/r52nhvys2_v1whps16vzs85c0000gn/T/d20160322-80022-1oihoos/file.zip https://cdn.firebase.com/ObjC/Firebase.framework-2.4.3.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to cdn.firebase.com port 443: Connection reset by peer

**Comment by amitburst** [comment]
Looks like you can't connect to cdn.firebase.com:443 for whatever. Is this a persistent issue? If so, it could be related to how your network is set up. This doesn't appear to be related to this project, though.
