### ISSUE TITLE
Investigate use of Firebase 3.0

### ISSUE THREAD

**Issue by amitburst** [amitburst/HackerNews#33]

**Comment by tuliot** [comment]
@amitburst have you started working on this?

**Comment by amitburst** [comment]
Hey, thanks for asking! I've only briefly looked through the documentation but it looks like in 3.0, you have to associate your app with a Firebase console app. I'm not so sure I want to go this route just yet because it adds more overhead to the set up of this project (in its current state, you simply install the dependencies and you're good to go).

I'll renaming this issue to "Investigate use of Firebase 3.0", but feel free to poke around the documentation and share anything interesting you find!

**Comment by amitburst** [comment]
Closing this out since I don't plan on maintaining this repository for the foreseeable future.
